Repository KyoshiNoda/ScheduleFinder, pull requests merged in 2023-04, with the labels that each got.

#96 92 create advanced user filtering
  client/src/components/findUsers/User.tsx
  client/src/components/findUsers/UserContainer.tsx
  client/src/pages/FindUser.tsx
Labels: Frontend

#97 Edit pagination button
  client/src/components/findUsers/User.tsx
  client/src/components/findUsers/UserContainer.tsx
  client/src/pages/FindUser.tsx
Labels: Frontend

#98 77 styling schedule with proper timeslot
  client/src/components/Login/LoginBox.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Navbar.tsx
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/components/Signup/SignUpBox.tsx
  client/src/components/Utils/ColorsPalette.tsx
  client/src/pages/Homepage.tsx
  client/src/pages/Schedule.tsx
Labels: Frontend, enhancement, fix

#100 Refactored Backend + Client Sync (JWT)
  backend/dist/controllers/AuthController.js
  backend/dist/controllers/ScheduleController.js
  backend/dist/routes/scheduleRoute.js
  backend/src/controllers/AuthController.ts
  backend/src/controllers/ScheduleController.ts
  backend/src/routes/scheduleRoute.ts
  client/src/components/Login/LoginForm.tsx
  client/src/components/Toggle.tsx
  client/src/redux/slices/SchedulesSlice.ts
Labels: Frontend, Backend, fix

#101 99 add time slot to schedule
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/pages/Schedule.tsx
Labels: Frontend

#106 Auth redux jwt
  backend/dist/controllers/AuthController.js
  backend/dist/routes/scheduleRoute.js
  backend/src/controllers/AuthController.ts
  backend/src/routes/scheduleRoute.ts
  client/src/components/Account/Personal/PersonalTab.tsx
  client/src/components/Account/Profile/ProfilePic.tsx
  client/src/components/Account/Profile/ProfileTab.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Navbar.tsx
  client/src/components/PageLayout.tsx
  client/src/main.tsx
  client/src/pages/Account.tsx
  client/src/pages/Login.tsx
  client/src/pages/Schedule.tsx
  client/src/pages/Signup.tsx
  client/src/redux/feats/auth/authActions.ts
  client/src/redux/feats/auth/authSlice.ts
  client/src/redux/feats/schedule/scheduleSlice.ts
  client/src/redux/services/auth/authService.ts
  client/src/redux/slices/UsersSlice.ts
  client/src/redux/store.ts
  client/src/redux/stores/schedulesStore.ts
  client/src/redux/stores/usersStore.ts
Labels: Frontend, Backend

#109 loaded user schedule with RTK Query
  client/src/pages/Schedule.tsx
Labels: Frontend

#112 111 create timeslot rtk query
  backend/dist/server.js
  backend/src/server.ts
  client/src/App.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/pages/Schedule.tsx
  client/src/redux/services/auth/authService.ts
  client/src/redux/services/schedule/scheduleService.ts
  client/src/redux/store.ts
Labels: Frontend

#114 113 typescript types file
  client/src/components/Account/Friends/FriendsTab.tsx
  client/src/components/Account/Profile/ProfilePic.tsx
  client/src/components/Auth/GoogleAuth.tsx
  client/src/components/Login/LoginBox.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Logos/Edit.tsx
  client/src/components/Logos/Github.tsx
  client/src/components/Logos/Moon.tsx
  client/src/components/Logos/Sun.tsx
  client/src/components/Navbar.tsx
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/components/Signup/SignUpForm.tsx
  client/src/components/Utils/ColorsPalette.tsx
  client/src/components/findUsers/UserContainer.tsx
  client/src/pages/FindUser.tsx
  client/src/pages/Login.tsx
  client/src/pages/Schedule.tsx
  client/src/redux/feats/auth/authActions.ts
  client/src/redux/feats/auth/authSlice.ts
  client/src/redux/feats/schedule/scheduleSlice.ts
  client/src/redux/services/schedule/scheduleService.ts
  client/src/types.ts
Labels: Frontend

#117 115 delete timeslot rtk query
  client/src/components/Schedule/DaysChecked.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/pages/Schedule.tsx
  client/src/redux/services/schedule/scheduleService.ts
  client/src/types.ts
Labels: Frontend

#118 76 compare timeslots
  backend/dist/controllers/ScheduleController.js
  backend/dist/routes/scheduleRoute.js
  backend/src/controllers/ScheduleController.ts
  backend/src/routes/scheduleRoute.ts
  client/src/App.tsx
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/components/findUsers/User.tsx
  client/src/main.tsx
  client/src/pages/CompareSchedule.tsx
  client/src/pages/Schedule.tsx
Labels: Frontend

#119 Fix issues
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/redux/feats/schedule/scheduleSlice.ts
Labels: fix

#120 116 update timeslot rtk query
  client/src/components/Schedule/DaysChecked.tsx
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/pages/Schedule.tsx
  client/src/redux/services/schedule/scheduleService.ts
  client/src/types.ts
Labels: Frontend

#122 107 add redux + jwt for register
  backend/dist/controllers/AuthController.js
  backend/dist/controllers/ScheduleController.js
  backend/dist/controllers/UserController.js
  backend/dist/models/userModel.js
  backend/dist/routes/authRoute.js
  backend/dist/routes/userRoute.js
  backend/src/controllers/AuthController.ts
  backend/src/controllers/ScheduleController.ts
  backend/src/controllers/UserController.ts
  backend/src/models/userModel.ts
  backend/src/routes/authRoute.ts
  backend/src/routes/userRoute.ts
  client/src/components/Login/LoginForm.tsx
  client/src/components/Signup/SignUpForm.tsx
  client/src/components/findUsers/User.tsx
  client/src/components/findUsers/UserContainer.tsx
  client/src/pages/FindUser.tsx
  client/src/redux/feats/auth/authActions.ts
  client/src/redux/feats/auth/authSlice.ts
  client/src/redux/feats/schedule/scheduleSlice.ts
  client/src/types.ts
Labels: Frontend, Backend

#124 121 edit find users page
  client/src/components/findUsers/LoadingUser.tsx
  client/src/components/findUsers/UserContainer.tsx
  client/src/index.css
Labels: Frontend

#126 Replace refresh
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/pages/Schedule.tsx
  client/src/redux/services/schedule/scheduleService.ts
  client/src/redux/store.ts
Labels: Frontend, fix

#129 127 fix time slot edit mode
  client/src/components/Schedule/TimeSlot.tsx
  client/src/pages/CompareSchedule.tsx
Labels: Frontend, fix

#136 Crud users rtk
  backend/dist/controllers/UserController.js
  backend/dist/routes/userRoute.js
  backend/src/controllers/UserController.ts
  backend/src/routes/userRoute.ts
  client/src/components/Account/Personal/PersonalTab.tsx
  client/src/components/Account/Profile/ProfilePic.tsx
  client/src/components/Account/Profile/ProfileTab.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/components/findUsers/UserContainer.tsx
  client/src/redux/services/user/userService.ts
  client/src/redux/store.ts
Labels: Frontend, Backend

#140 139 add favicon and change website title
  client/index.html
  client/src/components/Navbar.tsx
  client/src/pages/Homepage.tsx
Labels: Frontend
