Repository KyoshiNoda/ScheduleFinder, pull requests merged in 2023-03, with the labels that each got.

#58 55 set up basic redux
  backend/dist/controllers/ScheduleController.js
  client/src/redux/slices/SchedulesSlice.ts
  client/src/redux/slices/UsersSlice.ts
  client/src/redux/stores/schedulesStore.ts
  client/src/redux/stores/usersStore.ts
Labels: Backend

#60 2 create login page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/loggingOn.png
  client/src/assets/plsWork.png
  client/src/components/Login/LoginBox.tsx
  client/src/index.d.ts
  client/src/main.tsx
  client/src/pages/Homepage.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
  client/tailwind.config.cjs
  client/tsconfig.json
Labels: Frontend

#62 61 setup theme toggle + darklight
  client/package-lock.json
  client/package.json
  client/src/components/Login/LoginBox.tsx
  client/src/components/Logos/Moon.tsx
  client/src/components/Logos/Sun.tsx
  client/src/components/Toggle.tsx
  client/src/pages/Login.tsx
  client/src/redux/slices/UsersSlice.ts
  client/tailwind.config.cjs
Labels: Frontend, fix

#63 1 create signup page
  client/package-lock.json
  client/package.json
  client/src/assets/wavy-man-creating-a-website.png
  client/src/components/Auth/GoogleAuth.tsx
  client/src/components/Login/LoginBox.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Signup/SignUpBox.tsx
  client/src/components/Signup/SignUpForm.tsx
  client/src/pages/Signup.tsx
  client/tailwind.config.cjs
Labels: Frontend

#65 64 create tsx + styling account page
  client/src/App.tsx
  client/src/components/Account/AccountBox.tsx
  client/src/components/Account/ProfilePic.tsx
  client/src/components/Account/Tab.tsx
  client/src/components/Logos/Edit.tsx
  client/src/pages/Account.tsx
Labels: Frontend

#67 57 refactor server controllers
  backend/dist/controllers/ScheduleController.js
  backend/dist/controllers/UserController.js
  backend/src/controllers/ScheduleController.ts
  backend/src/controllers/UserController.ts
Labels: Backend, fix

#68 66 create route for tabs components
  client/src/components/Account/AccountBox.tsx
  client/src/components/Account/Password/PasswordTab.tsx
  client/src/components/Account/Personal/PersonalTab.tsx
  client/src/components/Account/Profile/ProfilePic.tsx
  client/src/components/Account/Profile/ProfileTab.tsx
  client/src/components/Account/Tab.tsx
  client/src/redux/slices/UsersSlice.ts
Labels: Frontend

#73 Fixing account styling
  client/src/components/Account/AccountBox.tsx
  client/src/components/Account/Personal/PersonalTab.tsx
  client/src/components/Account/Profile/ProfileTab.tsx
  client/src/components/Account/Tab.tsx
  client/src/index.css
  client/src/pages/Account.tsx
Labels: Frontend, fix

#79 Adding basic navbar layout. Some links are still missing.
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Account/AccountBox.tsx
  client/src/components/Account/Personal/PersonalTab.tsx
  client/src/components/Account/Tab.tsx
  client/src/components/Navbar.tsx
  client/src/pages/Account.tsx
Labels: Frontend

#81 80 fix responsiveness on pages
  client/src/components/Login/LoginBox.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Signup/SignUpBox.tsx
  client/src/pages/Login.tsx
  client/src/pages/Signup.tsx
Labels: Frontend, fix

#85 added new navbar on certain pages
  client/src/App.tsx
  client/src/components/PageLayout.tsx
Labels: Frontend, fix

#88 87 fix theme bug
  client/src/components/Toggle.tsx
  client/src/pages/Homepage.tsx
Labels: Frontend, fix

#89 added major field
  backend/dist/controllers/UserController.js
  backend/dist/models/userModel.js
  backend/src/controllers/UserController.ts
  backend/src/models/userModel.ts
Labels: Backend, fix

#95 93 create time slot generator component
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeBlockInput.tsx
  client/src/pages/Schedule.tsx
  client/src/redux/slices/UsersSlice.ts
Labels: Frontend
