Repository KyoshiNoda/ScheduleFinder, pull requests merged in 2023-09, with the labels that each got.

#192 168 Refactoring inputs in Time Slot Input component
  .prettierrc
  client/src/components/Schedule/TimeSlotInput.tsx
Labels: Fix

#194 fixed problem
  client/src/pages/CompareSchedule.tsx
Labels: Fix

#197 182 empty schedule clear
  backend/dist/controllers/ScheduleController.js
  backend/src/controllers/ScheduleController.ts
  client/src/components/Schedule/ClearScheduleButton.tsx
  client/src/components/Schedule/ScheduleBox.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
Labels: Frontend, tech-debt

#200 198 fix return single element
  backend/dist/controllers/ScheduleController.js
  backend/dist/controllers/UserController.js
  backend/src/controllers/ScheduleController.ts
  backend/src/controllers/UserController.ts
  client/src/components/Account/Personal/PersonalTab.tsx
  client/src/components/Account/Profile/ProfileTab.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/pages/CompareSchedule.tsx
Labels: Fix, tech-debt

#204 fixed smaller screens for courseTitle
  client/src/components/Schedule/TimeSlot.tsx
Labels: Fix

#206 199 fix UI for change password
  backend/dist/controllers/UserController.js
  backend/src/controllers/UserController.ts
  client/src/components/Account/Profile/ProfileTab.tsx
  client/src/components/Auth/ChangePassword.tsx
Labels: Fix

#209 207 fix landing page toggle
  client/src/components/Toggle.tsx
  client/src/pages/Account.tsx
  client/src/pages/FindUser.tsx
  client/src/pages/LandingPage.tsx
  client/src/pages/Notifications.tsx
  client/src/pages/Schedule.tsx
Labels: Frontend, Fix

#211 201 refactor day picker from timeslots
  client/src/components/Schedule/DayPicker.tsx
  client/src/components/Schedule/TimeSlot.tsx
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/types.ts
Labels: Frontend, tech-debt

#218 215 color accessibility on timeslotinput
  client/src/components/Schedule/TimeSlotInput.tsx
  client/src/components/Utils/ColorsPalette.tsx
Labels: Frontend, Fix
